spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashopsecond;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 #데이터가 별로 없을경우는 비추, 그럴 땐, V3을 사용
    #open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace